### ISSUE TITLE
App icons show as Essential Launcher icon before reverting to actual app icon when scrolling quickly down list

### ISSUE THREAD

**Issue by Pentaphon** [clemensbartz/essential-launcher#74]
### General Information

  * Essential Launcher Version: 2.1
  * Android Version: 7.1.2
  * Device with manufacturer: Moto G4
  * RAM: 2GB
  * App installed from: F-Droid
  
### Actual behavior
When scrolling quickly down the list of apps, the app icons are the Essential launcher icon for a moment until they become the actual app's icon. This doesn't happen when I scroll slowly down the list of apps, almost as if Essential takes too much time to render the icon when scrolling down the list quickly, but has enough time to render the icon when scrolling slowly. Is there any way to make sure the icons always stay the same when scrolling quickly instead of showing the Essential Launcher icon at all?

### Expected behavior

Icons should always remain as they are and not become the Essential launcher icon, even momentarily while scrolling.

**Comment by clemensbartz** [comment]
Yes and no. A future version will not show the icon but just have a blank icon. 

Icons are loaded asynchronously due to memory restrictions. I know that other launchers do not care and set „high memory“ flags, but I am not going to do that. Furthermore, on slower devices, it would even take more than 1 second if I loaded all icons beforehand. Neither are an option for me.

**Comment by clemensbartz** [comment]
#68 is already dealing with the former. Android itself is recycling old view and thus the icon must be „reloaded“ every single time. 

So closing for duplicate and won’t fix.
