### ISSUE TITLE
[enhancement] Allow to display many app icons in a grid

### ISSUE THREAD

**Issue by heinzelotto** [clemensbartz/essential-launcher#89]
I find it very useful to be able to launch most apps that I use with only a single tap from the home screen. For this, 5 or 7 icons are not quite enough. It would be nice to be able to display many more, with smaller icons, in multiple columns, ordered by usage count.

With this feature the user would be able to change the look and feel of the essential launcher a lot, but possibly much more accommodating to power users and efficiency freaks :robot: 

I tried it out and have been using it for quite a while already, in a 4x9 grid, and disabled landscape mode. I tweaked (these could be configurable):
- row count
- col count
- icon size (implicitly based on col count)
- added a "big increment counter" context menu option to increment the counter of an app by 10 for quicker reordering (this value is too small, after a few months it becomes tedious to move an app to the front e. g. after reinstall)

<img src="https://user-images.githubusercontent.com/5202835/79636223-6c38b080-8176-11ea-9f09-61e2643ce617.png" width="350" alt="multi column essential launcher">

**Comment by clemensbartz** [comment]
Hello,

First of all, thank you for taking the time to raise this. I have been thinking about this since you created the issue and have come to a conclusion. While I, myself, would also use that, most of the devices this app has been created for will not handle this kind of information very well. I already tried similar things on my test device (UniHertz Atom 4) which for me is the "gold-standard", but the small display makes this unusable. 

Of course, I could tweak the setting slightly to adjust for the device type, but even then I would still be left with comments saying that their device is not able to do all of it (already had it for the 7 icons). I am not even sure if an asynchronous, non-caching icon loading for more than 20 icons would result in reasonable reaction times on devices with only 16 MB of virtual RAM (https://source.android.com/compatibility/5.0/android-5.0-cdd.pdf). This is also the reason why the spacing between the icons in the list so huge…

If you take a look at #87 (hiding the dock), I think this is the direction I want to take this app.

So in the end, I would like to stick to mantra set forth in the README, that this is an app providing minimal functionality. 

Since you already tried that, feel free to create a fork, change the name and package and distribute it as your own app (keeping the license of course). Of course, you can also rely on the aforementioned improvements I will be doing to this app (including first of all quality checks in Sonar). 

I will leave this open for any comments you might have nd close it with the next release.

**Comment by heinzelotto** [comment]
Thanks for taking the time to explain! I see how it conflicts with keeping the launcher as light-weight as possible. Good idea on the fork, maybe someday I find the time to do it...
